export { default as Logo } from './svgs/logo.svg'
export { default as MenuSvg } from './svgs/Menu-Svg.svg'
export { default as LogoBlack } from './svgs/Logo-dark.svg'
export { default as Collections } from './svgs/Collections.svg'
export { default as Customers } from './svgs/Customers.svg'
export { default as Writers } from './svgs/Writers.svg'
export { default as Stores } from './svgs/Stores.svg'
export { default as Secure } from './svgs/Secure.svg'