# Generated by Django 5.0 on 2024-01-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Action/Fantasy', 'Action/Fantasy'), ('Adventure', 'Adventure'), ('History', 'History'), ('Animation', 'Animation'), ('Horror', 'Horror'), ('Biography', 'Biography'), ('Mystery', 'Mystery'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Sci-fi', 'Sci-fi'), ('Documentary', 'Documentary'), ('Sport', 'Sport')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ecommerce.category'),
        ),
    ]
