# Generated by Django 5.0 on 2024-01-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_year',
            field=models.DateField(),
        ),
    ]
