# Generated by Django 5.0 on 2024-01-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_product_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
