# Generated by Django 4.2.7 on 2024-01-22 03:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.DecimalField(decimal_places=1, default=Decimal('22'), max_digits=6),
        ),
    ]
