# Generated by Django 5.0 on 2024-01-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_category_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Action/Fantasy', 'Action/Fantasy'), ('Adventure', 'Adventure'), ('History', 'History'), ('Animation', 'Animation'), ('Horror', 'Horror'), ('Biography', 'Biography'), ('Mystery', 'Mystery'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Sci-fi', 'Sci-fi'), ('Documentary', 'Documentary'), ('Sport', 'Sport')], max_length=100, unique=True),
        ),
    ]
