# Generated by Django 4.2.7 on 2024-01-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.PositiveIntegerField(default=312),
        ),
    ]
